version: '3'

services: 
    db:
        image: 'postgres:11'
        ports:
            - '127.0.0.1:5432:5432'
        volumes:
            - 'pgdata:/var/lib/postgresql/data/'
        environment: 
            POSTGRES_PASSWORD: password
        
volumes:
    pgdata: